  <div class="row">
  <div class="col s12 ">
  <div class="card">
    <div class="card-image waves-effect waves-block waves-light">
       
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4"><i class="tiny material-icons large">business</i><?php echo $data['enterprise']; ?><i class="material-icons right">more_vert</i></span>
      <p><a href="/company">revient a la page companys</a></p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
      <p><strong>Enterprise id: </strong><?php echo $data['id'];  ?></p>
      <p><strong>Public : </strong><?php echo $data['public'];  ?></p>
      <p><strong>Nom Enterprise  : </strong><?php echo $data['enterprise'];  ?></p>
      <p><strong>Advertiser : </strong><?php echo $data['advertiser'];  ?></p>
      <p><strong>Provider : </strong><?php echo $data['provider'];  ?></p>
      <p><strong>Street : </strong><?php echo $data['street'];  ?></p>
      <p><strong>Number : </strong><?php echo $data['number'];  ?></p>
      <p><strong>Bus : </strong><?php echo $data['bus'];  ?></p>
      <p><strong>City : </strong><?php echo $data['city'];  ?></p>
      <p><strong>Postal : </strong><?php echo $data['postal'];  ?></p>
      <p><strong>Country : </strong><?php echo $data['country'];  ?></p>
      <p><strong>Invoice : </strong><?php echo $data['invoice'];  ?></p>
      <p><strong>Serviceprovider : </strong><?php echo $data['serviceprovider'];  ?></p>
    </div>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
  </div>
 </div>  
</div>