

<div class="row">
  <div class="col m12">
    <div class="card small z-depth-2  " id="log" style="height:auto; border-radius:10px;">

        <div class="row">
        <div style="width:100%;height:auto;padding:3px;margin:auto;background-color:teal;color:white" class=" center down col s12 m12 l12">
          <h5>la modification des entreprises</h5>    
          <i class="material-icons large">business</i>
        </div>
        </div>

      <form method="POST" name="users" action="/company/edit/<?php echo $data['id'];?>" role="form" id="company"> 
        <div class="row">
            <div class="switch col m12 center">
              Public : <label>Non<input <?php if($data['public']=='1'){echo 'checked="checked"'; } ?>  name="public"  type="checkbox" value="1"><span class="lever"></span>Oui</label>
           </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <input id="added"  name="added"  type="date" class="datepicker"  value="<?php echo $data['added'];?>">
            <label for="added">date début de validation</label>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12 ">
            <i class="material-icons prefix">spellcheck</i>
            <input  name="enterprise" id="enterprise" type="text"  autocomplete="on"    class="validate " value="<?php echo $data['enterprise'];?>">
           
          </div> <label for="enterprise">Nom Enterprise</label>
        </div>

        <div class="row">
          <div class="input-field col s12 ">
            <i class="material-icons prefix">spellcheck</i>
            <input  name="advertiser" id="advertiser" type="text"  autocomplete="on"   class="validate " value="<?php echo $data['advertiser'];?>">
            <label for="advertiser">Advertiser</label>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12 ">
            <i class="material-icons prefix">spellcheck</i>
            <input  name="provider" id="provider" type="text"  autocomplete="on"   class="validate " value="<?php echo $data['provider'];?>">
            <label for="provider">Provider</label>
          </div>
        </div>

         <div class="row">
          <div class="input-field col s12 ">
            <i class="material-icons prefix">spellcheck</i>
            <input  name="street" id="street" type="text"  autocomplete="on"   class="validate " value="<?php echo $data['street'];?>">
            <label for="street">Rue</label>
          </div>
        </div>

         <div class="row">
          <div class="input-field col s12 ">
            <i class="material-icons prefix">spellcheck</i>
            <input  name="number" id="number" type="text"  autocomplete="on"   class="validate " value="<?php echo $data['number'];?>">
            <label for="number">Number</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12 m6">
            <i class="material-icons prefix">spellcheck</i>
            <input  name="bus" id="bus" type="text"  autocomplete="on"   class="validate " value="<?php echo $data['bus'];?>">
            <label for="bus">Bus</label>
          </div>
          <div class="input-field col s12 m6">
            <i class="material-icons prefix">spellcheck</i>
            <input  name="city" id="city" type="text"  autocomplete="on"   class="validate " value="<?php echo $data['city'];?>">
            <label for="city">City</label>
          </div>
        </div>


      <div class="row">
          <div class="input-field col s12 m6">
            <i class="material-icons prefix">spellcheck</i>
            <input  name="postal" id="postal" type="text"  autocomplete="on"   class="validate" value="<?php echo $data['postal'];?>">
            <label >Postal</label>
          </div>
          <div class="input-field col s12 m6">
            <i class="material-icons prefix">spellcheck</i>
            <input  name="country" id="country" type="text"  autocomplete="on"   class="validate" value="<?php echo $data['country'];?>">
            <label for="country">Country</label>
          </div>
      </div>

       <div class="row">
          <div class="input-field col s12 m4">
            <i class="material-icons prefix">spellcheck</i>
            <input  name="btw" id="btw" type="text"  autocomplete="on"   class="validate" value="<?php echo $data['btw'];?>">
            <label for="btw">Btw</label>
          </div>
          <div class="input-field col s12 m4">
            <i class="material-icons prefix">spellcheck</i>
            <input  name="invoice" id="invoice" type="text"  autocomplete="on"   class="validate" value="<?php echo $data['invoice'];?>">
            <label for="invoice">Invoice</label>
          </div>
          <div class="input-field col s12 m4">
            <i class="material-icons prefix">spellcheck</i>
            <input  name="serviceprovider" id="serviceprovider" type="text"  autocomplete="on"   class="validate" value="<?php echo $data['serviceprovider'];?>">
            <label for="serviceprovider">Serviceprovider</label>
          </div>
      </div>

        <div class="row">
          <div class="col s4 m4 l4">.</div>
          <div class="col s4 m4 l4">
            <input  class="waves-effect waves-light btn" type="submit" name="company" value="Modifier">
          </div>
          <div class="col s4 m4 l4">.</div>
          <br>
        </div>
      </form>
    </div>
   </div>
  </div>
