<?php
$title = "L'Ajouter des pays";
$this->headTitle($title);
?>
<h1 class="center waves-effect waves-teal  ">L'Ajouter des pays</h1>

<?php
$form->setAttribute('action', $this->url('country', array('action' => 'add')));
$form->setAttribute('role', 'form');
$form->prepare();
?>

<br/><br/>
<div class="row">
  <div class="col  s12 m12 l12">
    <div class="card small hoverable" id="log" style="height:auto; border-radius:10px;">
     <?php echo $this->form()->openTag($form);  ?>
        <div class="row">
          <div class="input-field col s12">
            <?php echo $this->formHidden($form->get('id'));  ?>
          </div>

          <div class="input-field col s12">
            <i class="material-icons prefix">language</i>
            <?php echo $this->formRow($form->get('name'));  ?>
            <label for="nom">Nom pays: </label>
          </div>
        </div>
        <div class="row">
          <div class="col s4 m4 l4">.</div>
          <div class="col s4 m4 l4">
           <?php echo $this->formSubmit($form->get('submit'));  ?>
          </div>
          <div class="col s4 m4 l4">.</div>
          <br>
        </div>
       
      <?php echo $this->form()->closeTag();  ?>
    </div>
   </div>
  </div>
