 <?php
 $title = 'Les Pays';
 $this->headTitle($title);
 ?>
 <h1 class="center"><?php echo $this->escapeHtml($title); ?></h1>




 
<div class="row">
    <div class="col m2 l2 hide-on-small-only">.</div>
    <div class="col s12 m8 l8">
        <a class="waves-effect waves-red btn"  href="<?php echo $this->url('country', array('action'=>'add'));?>">Add new country</a>
    </div>
    <div class="col m2 l2 hide-on-small-only">.</div>
</div>

<!--hide-on-small-only -->
<div class="row">
    <div class="col m2 l2 hide-on-small-only">.</div>
    <div class="col s12 m8 l8">
        <table class="table hoverable">
         <tr>
             <th>Nom</th>
             <th>Operation</th>
         </tr>
         <?php foreach ($countrys as $country) : ?>
         <tr>
             <td><?php echo $this->escapeHtml($country->name);?></td>
             <td>
                 <a class="waves-effect waves-light btn" href="<?php echo $this->url('country',array('action'=>'edit', 'id' => $country->id));?>">Edit</a>
                 <a class="waves-effect waves-red btn" href="<?php echo $this->url('country',array('action'=>'delete', 'id' => $country->id));?>">Delete</a>
             </td>
         </tr>
         <?php endforeach; ?>
         </table>
    </div>
    <div class="col m2 l2 hide-on-small-only">.</div>
</div>
 

        