<div class="row">
  <div class="col m12">
    <div class="card small z-depth-2  " id="log" style="height:auto; border-radius:10px;">

        <div class="row">
        <div style="width:100%;height:auto;padding:3px;margin:auto;background-color:teal;color:white" class=" center down col s12 m12 l12">
          <h5>Formulaire d'ajout des utilisateurs</h5>    
          <i class="material-icons large">supervisor_account</i>
        </div>
        </div>

      <form method="POST" name="useradmin" action="/users/add" role="form" id="users"> 
        <div class="row">
           <div class="switch col m12 center">
               Active : <label>Non<input name="c1" type="checkbox" value="1"><span class="lever"></span>Oui</label>
           </div>
           <div class="switch col m12 center">
              Admin : <label>Non<input name="c2"  type="checkbox" value="1"><span class="lever"></span>Oui</label>
           </div>
            <div class="switch col m12 center">
              Public : <label>Non<input name="c3"  type="checkbox" value="1"><span class="lever"></span>Oui</label>
           </div>
        </div>
        <hr style="color:teal; width:50%; margin:auto; ">
        <div class="row">
            <div class="input-field col s12 m6">
              <select name="lang">
                <option value="" disabled selected>choisir votre option</option>
                <option value="1">french</option>
                <option value="2">dutch</option>
              </select>
              <label>Langue</label>
            </div>
          
           <div class="input-field col s12 m6">
              <select name="gend">
                <option value="" disabled selected>choisir votre option</option>
                <option value="1">M</option>
                <option value="2">F</option>
              </select>
              <label>Genre</label>
            </div>
        </div>



        <div class="row">
          <div class="input-field col s12 m6">
            <i class="material-icons prefix">spellcheck</i>
            <input name="name" id="name" type="text" class="validate">
            <label for="name">Nom</label>
          </div>
          <div class="input-field col s12 m6">
            <i class="material-icons prefix">spellcheck</i>
            <input name="lname" id="lname" type="text" class="validate">
            <label for="lname">Prenom</label>
          </div>
        </div>


        <div class="row">
          <div class="input-field col s12 m6">
            <i class="material-icons prefix">settings_phone</i>
            <input id="phone" name="phone" type="tel" class="validate">
            <label for="phone">Téléphone</label>
          </div>
          <div class="input-field col s12 m6">
            <i class="material-icons prefix">contact_phone</i>
            <input id="gsm" name="gsm" type="tel" class="validate">
            <label for="gsm">GSM</label>
          </div>
        </div>

        <div class="row">

          <div class="input-field col s12">
            <i class="material-icons prefix">email</i>
            <input id="email" name="email" type="text" class="validate">
            <label for="email">Email</label>
          </div>
          <div class="input-field col s12">
            <i class="material-icons prefix">vpn_key</i>
            <input id="password" name="password" type="password" class="validate">
            <label for="password">Password</label>
          </div>

           <div class="input-field col s12 m12">
              <select name="comp" class="browser-default">
                <option value="" disabled selected>choisir votre option</option>
                <?php
                    foreach ($datac as $cm) {
                       echo '<option value="'.$cm->id.'">'.$cm->enterprise.'</option>';
                    }
                ?>
              </select>
              <label>Company</label>
            </div>




         
        </div>
        <div class="row">
          <div class="col s4 m4 l4">.</div>
          <div class="col s4 m4 l4">
            <input  class="waves-effect waves-light btn" type="submit" name="users" value="Ajouter">
          </div>
          <div class="col s4 m4 l4">.</div>
          <br>
        </div>
      </form>
    </div>
   </div>
  </div>