<?php

if (isset($_GET['status']) && $_GET['status']=="y" ) {
  echo '<div class="card-panel green lighten-2">la désactivation a réussi</div>';
}

if (isset($_GET['status']) && $_GET['status']=="ydmn" ) {
  echo '<div class="card-panel green lighten-2">l admin a ete change pour affecte les changement se deconnecte et réessayer avec le nouveau compte admin</div>';
}


if (isset($_GET['status']) && $_GET['status']=="n" ) {
  echo '<div class="card-panel red lighten-2">vous devez specifier le code de lutilisateur pour le désactiver</div>';
}

if (isset($_GET['status']) && $_GET['status']=="ohh" ) {
  echo "<div class='card-panel red lighten-2'>probleme dans l'exécution de cette operation</div>";
}

if (isset($_GET['status']) && $_GET['status']=="filed_add" ) {
  echo "<div class='card-panel red lighten-2'>probleme dans l'ajout</div>";
}

if (isset($_GET['status']) && $_GET['status']=="y_add" ) {
  echo "<div class='card-panel green lighten-2'>l'ajout terminer</div>";
}

if (isset($_GET['status']) && $_GET['status']=="erreur_fetching_view_data" ) {
  echo "<div class='card-panel red lighten-2'>probleme de chargement des donnees</div>";
}

?>
<br/>
<a style="margin-left:100px;" href="/useradmin/adduser" class="waves-effect waves-teal btn ">Ajouter un utilisateur</a>
<br/><br/>
      <div class="row">
      <div class="col  s12 m12 l12">
          <table class="table hoverable">
            <thead>
              <tr>
                <th>genre</th>
                <th>nom</th>
                <th>prenom</th>
                <th>email</th>
                <th>langue</th>
                <th>phone</th>
                <th>gsm</th>
                <th>Désactivé</th>
              </tr>
            </thead>
            <tbody>
              <?php
              foreach ($data as $hist) {
              ?>
                    <tr>
                      <td><?php echo $hist->gender;?></td>
                      <td><?php echo $hist->name;?></td>
                      <td><?php echo $hist->firstname;?></td>
                      <td><?php echo $hist->email;?></td>
                      <td><?php echo $hist->lang;?></td>
                      <td><?php echo $hist->phone;?></td>
                      <td><?php echo $hist->gsm;?></td>
           <td>
<a data-position="bottom" data-delay="50" data-tooltip="désactiver cet utilisateur" class="tooltipped btn waves-effect waves-red" href="/useradmin/disableuser?iduser=<?php echo $hist->id; ?>">
              <i class="material-icons">power_settings_new</i>
           </a>
<a data-position="bottom" data-delay="50" data-tooltip="Faire de cet utilisateur un admin" class="tooltipped btn waves-effect waves-red" href="/useradmin/dmn?comp=<?php echo $hist->company ;?>&iduser=<?php echo $hist->id; ?>">
              <i class="material-icons">trending_down</i>
           </a>
           </td>
                    </tr>
              <?php }?>

            </tbody>
          </table>
      </div>
      </div>  


